version: 1
update_configs:
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "ci"
      include_scope: true
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true