name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    permissions: 
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # TODO: Remove
      - name: "Determine release version"
        uses: docker://ghcr.io/codfish/semantic-release-action:v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_URL: "https://api.github.com"

      - name: Set up java for tests execution
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle - build
        run: gradle build --info