name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    permissions: 
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up java for tests execution
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle - build & test
        run: sudo --preserve-env gradle build --info