name: CI/CD on master
on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: 
      contents: write # to allow pushing version tags
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up java for tests execution
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: "Determine release version"
        uses: docker://ghcr.io/codfish/semantic-release-action:v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_URL: "https://api.github.com"

      - name: Gradle - build & test
        run: sudo --preserve-env gradle build --info

      - name: Gradle - publish to GitHub packages
        if: env.RELEASE_VERSION != ''
        run: sudo --preserve-env gradle publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}